#!/bin/sh

set -e

BIN_NAME=@BIN_NAME@
MAJOR=@MAJOR_VERSION@
MINOR=@MINOR_VERSION@
FULL=@FULL_VERSION@
INFO_SUBDIR=@INFO_EMACSDIR@
INFOFILES="@INFO_FILES@"

for file in ${INFOFILES}
do
  install-info --quiet --remove-exactly ${INFO_SUBDIR}/${file} || true
done

# emacsen-common/emacs-remove used to be here.

(rmdir /usr/local/share/emacs/${FULL}/site-lisp 2>/dev/null && \
 rmdir /usr/local/share/emacs/${FULL}           2>/dev/null) || true

#DEBHELPER#

exit 0
